#!/usr/bin/perl -w

# pspmount - PSP mount/umount script
#            mounts psp to /mnt/psp by default
# Written by Aaron Blakely <aaron@ephasic.org>
#
# Distributed as part of PSPTools:
# http://github.com/ablakely/psptools

use strict;
use warnings;

my $mountpath = "/mnt/psp";
my $idx       = 0;

MODS:
if (not defined $ARGV[$idx]) { goto EXEC; }

if ($ARGV[$idx] eq "-V" || $ARGV[$idx] eq "-h" || $ARGV[$idx] eq "--help" || $ARGV[$idx] eq "--version") {
	print "\npspmount v0.5:  Automates the mounting process on systems which don't have automounting.\n";
	print "Written by Aaron Blakely <aaron\@ephasic.org>\n\n";
	print "Usage: $0 [-hp] [path]\n";
	print "  -h - Displays this message.\n";
	print "  -p [path] - Changes the mountpoint.\n\n";
	print "pspmount is distributed as part of the psptools package: http://github.com/ablakely/psptools\n\n";
	exit;
}

if ($ARGV[$idx] eq "-p" || $ARGV[$idx] eq "--path") {
	$mountpath = $ARGV[++$idx];

	$idx++;
	goto MODS;
}


EXEC:

if (`whoami` !~ /root/) {
	die "This program requires root!  Exiting...\n";
}

if (-e "$mountpath") {
	unless (system "sync && umount $mountpath && rmdir $mountpath") {
		exit;
	}
}

my $scsiID;
my $blockDev;
my @partitions;

print "Looking for PSP...\n";

my @pspgrep  = `dmesg | grep PSP`;

if ($pspgrep[-1] =~ /scsi (.*)/) {
	my @s = split(" ", $1);
	$scsiID = $s[0];
	$scsiID =~ s/\:$//;

	print "\nFOUND! \nADDR: $scsiID\n";
	my @bdlookup = `dmesg | grep '$scsiID'`;

	foreach my $lookup (@bdlookup) {
		if ($lookup =~ /$scsiID: \[(.*)\]/) {

			if (-e "/dev/$1") {
				print "Block Device: $1\n";
				my @pstrs = `dmesg | grep $1:`;
				my @pstr  = split(" ", $pstrs[-1]);

				print "Scanning for /dev/$1 partitions: \n";

				for (my $i = 3; $i < scalar @pstr; $i++) {
					print "  Found partition: /dev/$pstr[$i]\n";
					push(@partitions, $pstr[$i]);
				}

				print "Attempting to mount first partiton:";
				if (!-e "$mountpath") {
					system "mkdir $mountpath";
				}

				unless (system "mount -o rw,noauto,async,user,umask=1000 /dev/$partitions[0] $mountpath") {
					print " ok\n";
					print "\nPSP mounted to $mountpath\n";
					exit;
				}

			} else {
				die "Found PSP but it's not mountable!  Exiting.\n";
			}
		}
	}
} else {
	die "Can't find PSP in dmesg!  Exiting.\n";
}
